#!/bin/bash

# DisplayedRoomTemp
# Temperatura wewnetrzna

IDX=19
COMMAND=`ebusctl r -f -c 470 DisplayedHc1RoomTempDesired`
LOCALIP=$(hostname -I | cut -d' ' -f1)

#| cut -d\; -f1 | cut -d\" -f2`

IFS=';' read -r -a array <<< "$COMMAND"
TEMP="${array[0]}"

re='^-?[0-9]+([.][0-9]+)?$'
if [[ $TEMP =~ $re ]] ; then

#    current=$(curl -k -s "https://$LOCALIP/json.htm?type=devices&rid=$IDX" | jq -r '.result[] | .Data')

    #if [[ $current != "$TEMP C" ]] ; then
        curl -k -s "https://$LOCALIP/json.htm?type=command&param=udevice&idx=$IDX&nvalue=0&svalue=$TEMP"
    #else
#	echo "Update not needed"
#    fi
fi
