#!/bin/bash

# FanSpeed
# Prędkość wentylatora

IDX=71
COMMAND=`ebusctl r -f -c bai FanSpeed`
LOCALIP=$(hostname -I | cut -d' ' -f1)

re='^-?[0-9]+([.][0-9]+)?$'
if [[ $COMMAND =~ $re ]] ; then

#    current=$(curl -k -s "https://$LOCALIP/json.htm?type=devices&rid=$IDX" | jq -r '.result[] | .Data')
    
#    if [[ "$COMMAND RPM" != $current ]] ; then
        curl -k -s "https://$LOCALIP/json.htm?type=command&param=udevice&idx=$IDX&nvalue=0&svalue=$COMMAND"
#    else
#	echo "Update not needed"
#    fi
fi
