#!/bin/bash

IDX=70
energyhc1=`ebusctl r -f PrEnergySumHc1`
energyhwc1=`ebusctl r -f PrEnergySumHwc1`
LOCALIP=$(hostname -I | cut -d' ' -f1)

# empirically chosen dividers
dz_hwc1="672.730"
dz_hc1="747.0"

VALUE=$(echo "$energyhc1/$dz_hc1+$energyhwc1/$dz_hwc1" | bc -l | xargs printf %.0f)

curl -k -s "https://$LOCALIP/json.htm?type=command&param=udevice&idx=$IDX&nvalue=2&svalue=$VALUE"
