#!/bin/bash

# HcAutoOffPMode
# Stan wyłączenia

IDX=25
COMMAND=`ebusctl r -f -c 470 Hc1AutoOffMode`
LOCALIP=$(hostname -I | cut -d' ' -f1)

re='^[frostprotectioin|lowering|eco]*$'

if [[ $COMMAND =~ $re ]] ; then
    LEVEL=$(
	case $COMMAND in
	    "frostprotection") echo 10 ;;
	    "lowering") echo 20 ;;
	    "eco") echo 30 ;;
	esac)

    current=$(curl -k -s "https://$LOCALIP/json.htm?type=devices&rid=$IDX" | jq -r '.result[] | .Data')

    if [[ $current != "Set Level: $LEVEL %" ]] ; then
        curl -k -s "https://$LOCALIP/json.htm?type=command&param=switchlight&idx=$IDX&switchcmd=Set%20Level&level=$LEVEL"
    else
	echo "Update not needed"
    fi
fi