#!/bin/bash

# HeadCrve
# Krzywa Grzewcza

#TODO: zrobić obsługę tego floata

IDX=22
COMMAND=`ebusctl r -f -c 470 Hc1HeatCurve`
LOCALIP=$(hostname -I | cut -d' ' -f1)

IFS=';' read -r -a array <<< "$COMMAND"
VALUE="${array[0]}"

re='^-?[0-9]+([.][0-9]+)?$'
if [[ $VALUE =~ $re ]] ; then
#    current=$(curl -k -s "https://$LOCALIP/json.htm?type=devices&rid=$IDX" | jq -r '.result[] | .Data')
    if [[ $current != $VALUE ]] ; then
        curl -k -s "https://$LOCALIP/json.htm?type=command&param=udevice&idx=$IDX&nvalue=0&svalue=$VALUE"
    else
	echo "Update not needed"
    fi
fi
