#!/bin/bash
# Hc1DayTemp

IDX=17

NIGHTTEMP=`ebusctl r -f -c 470 Hc1NightTemp`
LOCALIP=$(hostname -I | cut -d' ' -f1)

re='^-?[0-9]+([.][0-9]+)?$'
if [[ $NIGHTTEMP =~ $re ]] ; then

#    current=$(curl -k -s "https://$LOCALIP/json.htm?type=devices&rid=$IDX" | jq -r '.result[] | .Data')

#    if [[ $current != $NIGHTTEMP ]] ; then
        curl -k -s "https://$LOCALIP/json.htm?type=command&param=udevice&idx=$IDX&nvalue=0&svalue=$NIGHTTEMP"
#    else
#	echo "Update not needed"
#    fi
fi