#!/bin/bash

# Hc1OPMode
# Stan grzania

IDX=21
COMMAND=`ebusctl r -f -c 470 Hc1RoomTempSwitchOn`
LOCALIP=$(hostname -I | cut -d' ' -f1)

re='^[off|modulating|thermostat]*$'

if [[ $COMMAND =~ $re ]] ; then
    LEVEL=$(
	case $COMMAND in
	    "off") echo 0 ;;
	    "modulating") echo 10 ;;
	    "thermostat") echo 20 ;;
	esac)

    current=$(curl -k -s "https://$LOCALIP/json.htm?type=devices&rid=$IDX" | jq -r '.result[] | .Data')

    if [[ $current != "Set Level: $LEVEL %" ]] ; then
	curl -k -s "https://$LOCALIP/json.htm?type=command&param=switchlight&idx=$IDX&switchcmd=Set%20Level&level=$LEVEL"
    else
	echo "Update not needed"
    fi
fi