#!/bin/bash

# StorageTemp
# Temperatura w bojlerze

IDX=6
COMMAND=`ebusctl r -f -c bai ReturnTemp`
LOCALIP=$(hostname -I | cut -d' ' -f1)

IFS=';' read -r -a array <<< "$COMMAND"
TEMP="${array[0]}"

re='^-?[0-9]+([.][0-9]+)?$'
if [[ $TEMP =~ $re ]] ; then
    echo "Kurwa mać"
    curl -k -s "https://$LOCALIP/json.htm?type=command&param=udevice&idx=$IDX&nvalue=0&svalue=$TEMP"
fi
